### ISSUE TITLE
runserver.py AttributeError: 'str' object has no attribute 'name' 

### ISSUE THREAD

**Issue by jeremydouglass** [fikipollo/PySiQ#2]
Steps to reproduce:

1. clone the latest master repo
2. set file permissions
3. add shebang `#!/usr/bin/env python` to the top of `runserver.py`
4. run `./runserver.py` on localhost
5. open `test/test_server.html` in web browser
6. submit a job through web page

Result:

Job submission fails, console server debug logs show a repeated polling error.

> File "/Users/user/git/pysiq-test/PySiQ/server.py", line 71, in check_status
>     return jsonify({'success': True, 'status': self.queue_instance.check_status(task_id).name})
> AttributeError: 'str' object has no attribute 'name'

Editing runserver.py and removing `.name` removes the error:

```
-  return jsonify({'success': True, 'status': self.queue_instance.check_status(task_id).name})
+  return jsonify({'success': True, 'status': self.queue_instance.check_status(task_id)})
```

Log:

```
180528:PySiQ $ ./runserver.py 
 * Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
INFO:werkzeug: * Running on http://0.0.0.0:8081/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/May/2018 18:15:43] "GET /server.cfg HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [28/May/2018 18:19:32] "GET /server.cfg HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [28/May/2018 18:22:27] "GET /api/enqueue HTTP/1.1" 405 -
INFO:werkzeug:127.0.0.1 - - [28/May/2018 18:24:27] "OPTIONS /api/enqueue HTTP/1.1" 200 -
DEBUG:root:New task Uu31312m1I added to queue.
DEBUG:root:Queue length 1
DEBUG:root:Notifying workers
DEBUG:root:Task dequeued.
DEBUG:root:Queue length 1
DEBUG:root:Worker wtiPTO41qQ4 starts working...
INFO:werkzeug:127.0.0.1 - - [28/May/2018 18:24:27] "POST /api/enqueue HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/May/2018 18:24:29] "OPTIONS /api/status/Uu31312m1I HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/May/2018 18:24:29] "GET /api/status/Uu31312m1I HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/pysiq/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/user/.virtualenvs/pysiq/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/user/.virtualenvs/pysiq/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/user/.virtualenvs/pysiq/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/user/.virtualenvs/pysiq/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/user/.virtualenvs/pysiq/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/user/.virtualenvs/pysiq/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/user/.virtualenvs/pysiq/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/user/.virtualenvs/pysiq/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/user/.virtualenvs/pysiq/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/git/pysiq-test/PySiQ/server.py", line 71, in check_status
    return jsonify({'success': True, 'status': self.queue_instance.check_status(task_id).name})
AttributeError: 'str' object has no attribute 'name'
```

**Comment by fikipollo** [comment]
Thanks for the report, I've fixed in the new version (0.4, in development now).
